import Sidebar from '@/components/admin/Sidebar';
import AdminTabContent from '@/components/admin/tab/AdminTabContent';
import ShadToaster from '@/components/ui/toaster';
import Head from 'next/head';
import { useRouter } from 'next/router';



export default function Tab() {
  const router = useRouter()
  const tab = router?.query?.tab || "home"
  return (
    <Sidebar active={tab}>
      <Head>
        <title>Admin</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <AdminTabContent activeTab={tab}/>
    </Sidebar>
  );
}
